### ISSUE TITLE
Need to resolve vulnerabilities

### ISSUE THREAD

**Issue by NikithShetty** [NikithShetty/sever-side-V_Group#3]

**Comment by slavabez** [comment]
What are the vulnerabilities? Are they to do with outdated NPM packages?

**Comment by NikithShetty** [comment]
@slavabez yes

**Comment by slavabez** [comment]
Ok, I'll have a go at fixing using NPM's audit functionality

**Comment by slavabez** [comment]
I used `npm audit` to fix the critical dependency vulnerabilities. There are still some left, but all the critical ones are gone
